name: CD
on:
  push:
    branches:
      - main
      - backport/*.*
    paths:
      - config/**
      - spack.yaml
jobs:
  cd:
    name: CD
    uses: access-nri/build-cd/.github/workflows/cd.yml@v2
    with:
      model: ${{ vars.NAME }}
      root-sbd: access-esm1p5
    permissions:
      contents: write
    secrets: inherit
